# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZGaSLM5oQiQtMskhrgg7DYVmKp-jZtA

* Pyplot is a class in matplotlib library
# Normal Graph
"""

from matplotlib import pyplot as plt
plt.plot([1,3,5],[4,8,2])
plt.title('Info')
plt.xlabel('X-axis')
plt.ylabel("Y-axis")
plt.show()

"""*We can change Background of  a graph by using style class*"""

import matplotlib.pyplot as plt
from matplotlib import style
style.use('dark_background')
x=[1,2,3]
y=[5,4,1]
plt.plot(x,y)
plt.show()

"""*For changing Colour of X and Y*
**A single letter string, i.e. one of {'b', 'g', 'r', 'c', 'm', 'y', 'k', 'w'}, which are short-hand notations for shades of blue, green, red, cyan, magenta, yellow, black, and white**

**legend will give You a label of X and Y that what is representating what.**
"""

import matplotlib.pyplot as plt
x=[1,2,3]
y=[5,4,1]
x1=[7,2,4]
y1=[2,8,6]
plt.title('super')
plt.plot(x,y,label='line',color='k')
plt.plot(x1,y1,label='line2',color='g')

plt.xlabel('X-axis')
plt.ylabel('Y-Axis')
plt.legend()
plt.show()

"""# Vizualization using Numpy Array"""

from matplotlib import pyplot as plt
import numpy as np
x=np.arange(1,11)
y=np.arange(1,11)
plt.plot(x,y)
plt.show()

"""# Scatter Plot using numpy"""

from matplotlib import pyplot as plt
from matplotlib import style

import numpy as np
style.use('default')

x=np.array([1,7,8,5,6])
y=np.array([5,7,9,4,3])

plt.scatter(x,y)
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.title('Scatter Plot')
plt.show()

"""# Scatter plot using Random Numpy"""

import matplotlib.pyplot as plt
import numpy as np
x=np.random.randint(100,size=(50))
y=np.random.randint(100,size=(50))
plt.scatter(x,y)
plt.xlabel("X-Axis")
plt.ylabel('Y-Axis')
plt.title('Scatter Plot with Random')
plt.show()

"""[For More about Matplotlib Click Me](https://matplotlib.org/stable/gallery/index.html#)"""